services:
  - type: web
    name: institute
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn coach_saas_app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production